### ISSUE TITLE
Tone town logging even more

### ISSUE THREAD

**Issue by mraible** [jhipster/generator-jhipster-native#10]
I tried this in a recent example and found that it logs quite a few messages in the console. I was able to get it down to a reasonable level with the following. It's still more than I'd like, but I'm not sure how to suppress the others.

```yaml
logging:
  level:
    root: ERROR
    io.netty: ERROR
    liquibase: ERROR
    org.hibernate: ERROR
    org.springframework: ERROR
    com.zaxxer.hikari: ERROR
    org.apache.catalina: ERROR
    org.apache.tomcat: ERROR
    tech.jhipster.config: ERROR
    jdk.event.security: ERROR
    java.net: ERROR
    sun.net.www: ERROR
```
<img width="1915" alt="Screen Shot 2022-02-16 at 17 58 56" src="https://user-images.githubusercontent.com/17892/154383710-9e9dfd2d-4223-4a89-951e-51a0559a66d8.png">
