### ISSUE TITLE
Why is zipkin added?

### ISSUE THREAD

**Issue by mraible** [jhipster/generator-jhipster-native#9]
I don't have Zipkin in my project's `.yo-rc.json`. However, when I run this blueprint, it adds one for Docker Compose. 

```yaml
# This configuration is intended for development purpose, it's **your** responsibility to harden it for production
version: '3.8'
services:
  zipkin:
    image: openzipkin/zipkin:2.23
    ports:
      - 127.0.0.1:9411:9411
```

**Comment by mshima** [comment]
Added at https://github.com/jhipster/generator-jhipster/pull/17615
Since we already had the dependency, the docker compose file made sense.

**Comment by mraible** [comment]
Shouldn't it only be included if you're using service discovery, it's a gateway, or it's a microservice? This app is a monolith without service discovery. Here's the logic from [`application-dev.yml`](https://github.com/jhipster/generator-jhipster/blob/main/generators/server/templates/src/main/resources/config/application-dev.yml.ejs#L256):

```yaml
<%_ if (serviceDiscoveryType || applicationTypeGateway || applicationTypeMicroservice) { _%>
  sleuth:
    # https://github.com/spring-projects/spring-framework/issues/27844#issuescomment-1002866885
    # https://github.com/spring-cloud/spring-cloud-sleuth/issues/2094
    async:
      enabled: false
    enabled: false
    sampler:
      probability: 1 # report 100% of traces
  zipkin: # Use the "zipkin" Maven profile to have the Spring Cloud Zipkin dependencies
    base-url: http://localhost:9411
    enabled: false
    locator:
      discovery:
        enabled: true
<%_ } _%>
```
